Esther/gp 70/output group chat record
Fang-4-Group/Graduation-Project pull request #21
Opened 2024-05-04 15:46 UTC by Esther125

## Test：Output Group Chat Records
### Prerequisities
You should follow the steps  in the README.md to update Webhook URL in LINE Developers settings.

### Steps
Update the `.env` file
```
MONGO_DB_NAME=Graduation-Project
MONGO_COLLECTION=group-chat-record
```
Run the app
```
cd src\chatbot
python main.py
```
Create a group and add the official account to it. Any message sent to the group will be saved to MongoDB. All the message records from the group will be logged to the console.
### Sample Result
  <img width="704" alt="測試成功" src="https://github.com/Fang-4-Group/Graduation-Project/assets/82760846/b7e97290-a82f-4b90-b996-7dce2f3908bc">

2024-05-06 05:19 UTC, frafishen commented
pls also update the `example.env`

2024-05-06 05:38 UTC, frafishen commented
I'm not really sure if I missed some steps, cuz I got the error msgs below after adding the chatbot into the group.

```
INFO:     192.168.65.1:24623 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/srv/graduation-project/src/chatbot/main.py", line 48, in line_webhook
    and event["message"]["type"] == "text"  # noqa
KeyError: 'message'

```

2024-05-06 05:45 UTC, Esther125 commented
It seems that your event variable is out of format. Could you try to print out the events variable at line 43 in main.py? Thanks.

2024-05-06 05:50 UTC, frafishen requested changes

2024-05-06 05:50 UTC, frafishen commented on src/chatbot/main.py
The functional functions and the routing functions should not be in the same file.

2024-05-06 05:50 UTC, frafishen commented on src/chatbot/main.py
> +
Also these two

2024-05-06 05:50 UTC, frafishen commented on src/chatbot/main.py
> +
Consider prefixing routing paths for the Line chatbot to distinguish them clearly from the DB CRUD operations. 

add a line like
`router = APIRouter(prefix="/linebot")`

2024-05-06 05:53 UTC, frafishen commented
> ld you try to print out the events variable at line 43 in main.py? Thanks.

quite normal???

------------------------------------------
[{'type': 'join', 'webhookEventId': '01HX67BBXNN485S272F5FQJMAX', 'deliveryContext': {'isRedelivery': False}, 'timestamp': 1714974731884, 'source': {'type': 'group', 'groupId': 'C37cf80e16fe3f373a1b6957dbe3870cb'}, 'replyToken': 'b271174fd3e9482e827ff157e0dbb3b9', 'mode': 'active'}]
------------------------------------------

2024-05-06 06:38 UTC, Esther125 commented
Normal message event looks like this:
```
EVENTS: [{'type': 'message', 'message': {'type': 'text', 'id': '506916745496756691', 'quoteToken': 'Ywa8ompgBK3auvkcRRBVUXqO_uy5AWRHBgexWDN7PxtcuRIyhY9BGc2Wrpkm48AdIfCuklxTEpRkqlUb2VyfLBqFbWaawjRRJb_LTHoczMTD61UkS9rZ-4JuaCCZ5xhk0sFugFrlcG8BRqM0WNR16g', 'text': '一樣'}, 'webhookEventId': '01HX69QK5P79J2K2HG7CPVX7QK', 'deliveryContext': {'isRedelivery': False}, 'timestamp': 1714977229501, 'source': {'type': 'group', 'groupId': 'Cdebbc45c673946cb3c85fb5ea318e0ab', 'userId': 'U55370f7ef8ef0a0b9a826a7e2e0fa5ba'}, 'replyToken': '2e1906ce73b34ae89b35b2b63c5b71d9', 'mode': 'active'}]
```
Your event is related to joining the group. You can just ignore it, restart the server, and start to send message to the group to test it. I will add a part to ignore joining event to fix the exception.

2024-05-06 07:13 UTC, yun-si commented
I also got Error Message when adding the Line bot into a group.
```
INFO:     172.18.0.1:43830 - "POST /callback HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/srv/graduation-project/src/chatbot/main.py", line 48, in line_webhook
    and event["message"]["type"] == "text"  # noqa
KeyError: 'message'
Exception: object UpdateResult can't be used in 'await' expression
```

✨✨But the message record output is success.
```
----------------------------------------
FROM MONGO DB: {'_id': ObjectId('6638817eed161db61bb6a7e6'), 'groupId': '...', 'messages': [{'UserId': '...', 'UserName': '林耘熙', 'MsgText': 'hihi ', 'Time': datetime.datetime(2024, 5, 6, 7, 6, 38, 722000)}]}
```
ps. I don't know whether the id can be public, so I replace it to ... manually.

2024-05-06 08:56 UTC, Esther125 commented on src/chatbot/main.py
Done.

2024-05-07 01:52 UTC, frafishen commented
Also works fine here!!!

2024-05-07 01:53 UTC, frafishen approved these changes

2024-05-07 02:02 UTC, frafishen requested changes
add the package of `service` into the `requirements.txt` in the root.
Rebuild the docker image, and the `uvicorn src.chatbot.main:app --host localhost --port 8080 --reload` can run well.
<img width="386" alt="image" src="https://github.com/Fang-4-Group/Graduation-Project/assets/104518723/f329a066-5715-47de-b237-fa4d0900f413">

<img width="917" alt="image" src="https://github.com/Fang-4-Group/Graduation-Project/assets/104518723/afe1e0e6-267f-4358-8726-fd2b8d487dfe">

2024-05-07 02:16 UTC, frafishen approved these changes

2024-05-07 02:17 UTC, frafishen commented
> add the package of `service` into the `requirements.txt` in the root. Rebuild the docker image, and the `uvicorn src.chatbot.main:app --host localhost --port 8080 --reload` can run well. 

I forgot we have a ticket already.
This PR is fine!!
https://frafishen.atlassian.net/browse/GP-83

2024-05-07 03:54 UTC, merged