Jenny/gp 83/create hot reload for frontend
Fang-4-Group/Graduation-Project pull request #26
Opened 2024-05-10 15:34 UTC by frafishen

- fix the error that the chatbot cannot be built by uvicorn by adding the `services` package in the `requirements.txt`
- fix the error that the `"@line/liff"` would cause the error when `npm run serve` during the frontend building

## Warning (?
I'm not sure if the hot reload is an issue because the hot reload can run well on my side.

2024-05-14 13:58 UTC, yun-si reviewed
I got the error message when building the container.

I have run `docker system prune` before rebuilding the container.
```
[+] Building 12.6s (13/14)              docker:default
 => [frontend internal] load build definition fr  0.5s
 => => transferring dockerfile: 292B              0.0s 
 => [app internal] load build definition from Do  0.4s
 => => transferring dockerfile: 499B              0.0s
 => ERROR [frontend internal] load metadata for  12.0s
 => [app internal] load metadata for docker.io/l  4.8s 
 => [app internal] load .dockerignore             0.0s
 => => transferring context: 2B                   0.0s 
 => [app 1/8] FROM docker.io/library/python:3.10  0.0s 
 => [app internal] load build context             5.5s 
 => => transferring context: 131.36MB             5.4s 
 => CACHED [app 2/8] WORKDIR /srv/graduation-pro  0.0s
 => CACHED [app 3/8] RUN apt-get update           0.0s 
 => CACHED [app 4/8] RUN apt-get install -y wget  0.0s 
 => CACHED [app 5/8] RUN rm -rf /var/lib/apt/lis  0.0s 
 => [app 6/8] COPY ./requirements.txt ./          0.5s 
 => CANCELED [app 7/8] RUN pip install -r requir  1.2s
------
 > [frontend internal] load metadata for docker.io/library/node:lts:
------
failed to solve: node:lts: failed to resolve source metadata for docker.io/library/node:lts: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/lts": net/http: TLS handshake timeout
```

2024-05-19 05:34 UTC, yun-si commented
Hot reload still doesn't work on my computer

2024-05-19 10:38 UTC, yun-si requested changes
The hot reload works.
But vscode need some setting

### Steps
1. open setting of vscode
2. search `security.allowedUNCHosts`
3. click Add item, and fill in `wsl.localhost`

Then you can directly drag the folder to vscode for opening

I think this can be add to README.md

2024-05-19 12:24 UTC, frafishen commented
@yun-si @Esther125 @DanielYang1209 @Jeaninetang 
I've updated the readme.
pls help me check again, especially those who need frontend hot reload.

2024-05-19 15:02 UTC, yun-si approved these changes

2024-05-19 16:11 UTC, merged