Esther/gp 63/third party sign in
Fang-4-Group/Graduation-Project pull request #27
Opened 2024-05-11 13:26 UTC by Esther125

## Pull Request: Test Google OIDC Login

### Prerequisites
- Navigate to the Google Cloud API Credentials page at [Google Cloud Console](https://console.cloud.google.com/apis/credentials?hl=en) and create a new project.
- Follow the instructions on this page to register a client: [Google OAuth 2.0 Integration Guide](https://growingdna.com/google-oauth-2-0-for-3rd-party-login/). Please set two redirect URIs: `http://localhost:8082/google-oidc/auth` and `http://localhost:8082/google-oidc/login`.
- After registering, add yourself as a test user and download the OAuth client JSON file. Rename this file to `client.json` and place it under the `packages/google-oidc` directory.

### Steps to Test
1. Switch to my branch:
   ```bash
   git checkout esther/GP-63-third-party-sign-in
   ```
2. Start the test environment:
   ```bash
   # Accessing the container's shell
   docker exec -it graduation-project /bin/bash

   cd packages
   cd google-oidc
   python oidc.py
   ```
3. Visit [http://localhost:8082/google-oidc/](http://localhost:8082/google-oidc/) to see the test results.

### Expected Results
<img width="400" alt="homepage" src="https://github.com/Fang-4-Group/Graduation-Project/assets/82760846/2e4be7b3-a888-4b8e-b7ef-db35f8792647">
<img width="400" alt="login" src="https://github.com/Fang-4-Group/Graduation-Project/assets/82760846/04228ea1-6fe4-4115-9751-814f1780f49e">
<img width="400" alt="login-successful" src="https://github.com/Fang-4-Group/Graduation-Project/assets/82760846/ab909842-d764-4e53-b1ab-9fad6f1050cb">

2024-05-14 14:25 UTC, yun-si approved these changes
success~

2024-05-19 12:42 UTC, frafishen requested changes
Pls also add the test for the google-oidc.

2024-05-19 12:42 UTC, frafishen commented on .gitignore
I think `client.json` should also be contained.

2024-05-19 12:42 UTC, frafishen commented on packages/google-oidc/oidc.py
The client of `google-oidc` should be an independent Class (just like [`PosgresqTestClient`](https://github.com/Fang-4-Group/Graduation-Project/blob/master/database/seeds/pg_api_for_testing.py)), which should be stored in the path of `./src/services/google/google_oidc.py`, and be used in the [`route.py`](https://github.com/Fang-4-Group/Graduation-Project/blob/master/src/app/route.py) to divide the functions and routing.

2024-05-25 12:14 UTC, Esther125 commented on packages/google-oidc/oidc.py
Done.

2024-05-26 14:15 UTC, frafishen approved these changes
update the `.gitignore` and  `readme`, and it's ok to merge~

2024-05-26 14:21 UTC, merged