Jeaninetang/gp 65/store profile into db 2
Fang-4-Group/Graduation-Project pull request #29
Opened 2024-05-14 16:16 UTC by Jeaninetang

**Change**

- Add six vue components
- Move LIFF component to route
- Add route apis
- Connect frontend and backend

**Test**

- If you want to change path, you can go to this place, which is in index.js, to look up which path you should route to 
![image](https://github.com/Fang-4-Group/Graduation-Project/assets/94062751/c7c3288c-8821-4f2a-b1cf-8c5a8c02097b)

2024-05-19 12:32 UTC, frafishen commented
There are some errors.
Did I miss something?

```bash
╰─ docker exec -it graduation-project-frontend-1 /bin/bash
root@8bc1de03c015:/app# npm run serve

> frontend@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...


 ERROR  Failed to compile with 2 errors                                                                                                                                     12:29:50 PM

 error  in ./src/components/EditBasic.vue?vue&type=script&setup=true&lang=js

Module not found: Error: Can't resolve 'vue-router' in '/app/src/components'

 error  in ./src/router/index.js

Module not found: Error: Can't resolve 'vue-router' in '/app/src/router'

ERROR in ./src/components/EditBasic.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/EditBasic.vue?vue&type=script&setup=true&lang=js) 3:0-39
Module not found: Error: Can't resolve 'vue-router' in '/app/src/components'
 @ ./src/components/EditBasic.vue?vue&type=script&setup=true&lang=js 1:0-212 1:0-212 1:213-414 1:213-414
 @ ./src/components/EditBasic.vue 2:0-71 3:0-66 3:0-66 8:49-55
 @ ./src/router/index.js 4:0-52 18:13-22
 @ ./src/main.js 6:0-30 12:8-14

ERROR in ./src/components/EditHousePref.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/EditHousePref.vue?vue&type=script&setup=true&lang=js) 3:0-39
Module not found: Error: Can't resolve 'vue-router' in '/app/src/components'
 @ ./src/components/EditHousePref.vue?vue&type=script&setup=true&lang=js 1:0-216 1:0-216 1:217-422 1:217-422
 @ ./src/components/EditHousePref.vue 2:0-75 3:0-70 3:0-70 8:49-55
 @ ./src/router/index.js 5:0-60 27:13-26
 @ ./src/main.js 6:0-30 12:8-14

ERROR in ./src/components/EditInterests.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/EditInterests.vue?vue&type=script&setup=true&lang=js) 3:0-39
Module not found: Error: Can't resolve 'vue-router' in '/app/src/components'
 @ ./src/components/EditInterests.vue?vue&type=script&setup=true&lang=js 1:0-216 1:0-216 1:217-422 1:217-422
 @ ./src/components/EditInterests.vue 2:0-75 3:0-70 3:0-70 8:49-55
 @ ./src/router/index.js 6:0-60 24:13-26
 @ ./src/main.js 6:0-30 12:8-14

ERROR in ./src/components/EditPersonality.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/EditPersonality.vue?vue&type=script&setup=true&lang=js) 3:0-39
Module not found: Error: Can't resolve 'vue-router' in '/app/src/components'
 @ ./src/components/EditPersonality.vue?vue&type=script&setup=true&lang=js 1:0-218 1:0-218 1:219-426 1:219-426
 @ ./src/components/EditPersonality.vue 2:0-77 3:0-72 3:0-72 8:49-55
 @ ./src/router/index.js 7:0-64 21:13-28
 @ ./src/main.js 6:0-30 12:8-14

ERROR in ./src/router/index.js 1:0-60
Module not found: Error: Can't resolve 'vue-router' in '/app/src/router'
 @ ./src/main.js 6:0-30 12:8-14

webpack compiled with 5 errors
```

2024-05-19 16:02 UTC, frafishen commented
after `npm update`
![image](https://github.com/Fang-4-Group/Graduation-Project/assets/104518723/b04c2195-6439-40fe-80a5-b0b2ae0e4a2b)

2024-06-05 03:30 UTC, yun-si commented on database/migrations/pg_CRUD.py
> +                return {"message": furniture_list}
We have remove the Preference_House_Furniture.
Why there is a furniture_list here?

2024-06-05 10:43 UTC, frafishen requested changes
It appears that the definitions for the db operations, specifically for saving information, are incomplete. Please consider either creating a new ticket to address these operations or completing them within the scope of this current ticket.

2024-06-05 10:43 UTC, frafishen commented on database/migrations/pg_CRUD.py
> +        async with self.access_db() as conn:
the question about the `furniture` is same as the above

2024-06-05 10:43 UTC, frafishen commented on database/migrations/pg_CRUD.py
> +    async def add_preference_house_furniture(
the question about the furniture is same as the above

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditHouseBasic.vue
> +    // 保存房屋基本資料的逻辑
there's no operation for the HouseData here?

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditHousePref.vue
> +
- What is the primary goal of this ticket? 
- If the intention is to store information in the db, should there not be a `saveUserData` method defined in the code? 
- Currently, it seems that the class for db operations has been defined but not utilized within the scope of this ticket. Is the focus of this ticket solely on the frontend design, with the intention to handle database operations in a separate ticket?

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditHouseFurniture.vue
> +        <form @submit.prevent="saveFurnitureData">
where is the definition of `saveFurnitureData`?

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditHouseTraffic.vue
> +        <form @submit.prevent="saveTransportData">
definition of `saveTransportData`

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditInterests.vue
> +      <form @submit.prevent="saveUserData">
definition of `saveUserData`

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/EditPersonality.vue
> +        <form @submit.prevent="saveUserData">
definition or the import for `saveUserData`

2024-06-05 10:43 UTC, frafishen commented on frontend/src/components/FirstPage.vue
> +//   // 你的提交表單邏輯
so you are not going to define this in this ticket?

2024-06-05 10:43 UTC, frafishen commented on frontend/src/main.js
> +app.use(router);
Please remove any commented-out code if it will not be used in future developments.
If these commented sections relate to unfinished tasks, add a `TODO:` comment specifying the work to be completed, and include a link to the relevant ticket for context, like this:

``` 
// TODO: Complete the unfinished functions related to ... as outlined in ticket [URL_of_ticket].
```

2024-06-05 10:43 UTC, frafishen commented on src/app/route.py
> +# @router.put("/update_sleep_time/{people_id}")
link a `TODO` label here to remind others?

2024-06-07 13:48 UTC, Jeaninetang commented on frontend/src/main.js
> +app.use(router);
ok

2024-06-07 13:48 UTC, Jeaninetang commented on frontend/src/components/FirstPage.vue
> +//   // 你的提交表單邏輯
ok

2024-06-07 13:48 UTC, Jeaninetang commented on frontend/src/components/EditPersonality.vue
> +        <form @submit.prevent="saveUserData">
ok

2024-06-07 13:49 UTC, Jeaninetang commented on frontend/src/components/EditInterests.vue
> +      <form @submit.prevent="saveUserData">
ok

2024-06-07 13:49 UTC, Jeaninetang commented on frontend/src/components/EditHouseFurniture.vue
> +        <form @submit.prevent="saveFurnitureData">
ok

2024-06-07 13:49 UTC, Jeaninetang commented on frontend/src/components/EditHousePref.vue
> +
ok

2024-06-07 13:50 UTC, Jeaninetang commented on frontend/src/components/EditHouseBasic.vue
> +    // 保存房屋基本資料的逻辑
ok

2024-06-07 13:52 UTC, Jeaninetang commented on database/migrations/pg_CRUD.py
> +    async def add_preference_house_furniture(
Deleted add_preference_house_furniture complete

2024-06-07 13:53 UTC, Jeaninetang commented on database/migrations/pg_CRUD.py
> +                return {"message": furniture_list}
ok, I have removed the get_elder_info since I found that I have no need to use this api.

2024-06-07 14:01 UTC, Jeaninetang commented on src/app/route.py
> +# @router.put("/update_sleep_time/{people_id}")
Ok

2024-06-07 15:48 UTC, frafishen approved these changes
It's OK to merge!!! (cc: @yun-si )

2024-06-07 16:08 UTC, merged