Yunsi/gp 23/create db
Fang-4-Group/Graduation-Project pull request #8
Opened 2024-03-30 11:22 UTC by yun-si

## DB 測試步驟

1. 切換到 yunsi/GP-11/Create-db 分支
2. git pull
3. 跑下面的指令
    
    ```docker
    # Building the Docker image
    make docker-build
    
    # If there's no "make" command in your environment
    docker-compose build
    
    # Deploying the service using Docker Compose
    docker-compose up -d
    
    # Accessing the container's shell
    docker exec -it graduation-project /bin/bash
    ```
    
    跑完後應該會類似這樣
    
    ```root@d17884b2684b:/srv/graduation-project#```
    
4. 執行測試檔
    1. PosgreSQL Testing
        
        ```docker
        cd scr/db
        
        python test.py
        ```
        
        出現右圖就算成功了  <img width="131" alt="Untitled (4)" src="https://github.com/Fang-4-Group/Graduation-Project/assets/93365070/0f914bad-fec5-458d-9d67-1a60e8be5e52">

        
        
    2. Mongodb Testing
        
        ```docker
        cd scr/db
        
        python test_mongodb.py
        ```
        
        出現右圖就算成功了<img width="153" alt="Untitled (5)" src="https://github.com/Fang-4-Group/Graduation-Project/assets/93365070/ebba0c9e-cb19-4e2c-8f30-c4f727582129">

## pgAdmin testing

1. 執行過上方指令
2. 在 Docker Destop 中點擊連結
    
<img width="533" alt="Untitled (6)" src="https://github.com/Fang-4-Group/Graduation-Project/assets/93365070/9aa6cb73-f296-4598-82ef-548b66ad29f4">

3. 登入
    
    帳號： [riceball@gmail.com](mailto:riceball@gmail.com)
    
    密碼：gp12345
    
4. 點擊 Add New Server
    
    **General**
    
    Name: PosgreSQL-gp
    
    **Connection**
    
    Host Name/Address: postgres_db
    
    Port: 5432
    
    Username: riceball
    
    **Click Save**
    
5. 右側出現下圖就成功了    
<img width="182" alt="Untitled (7)" src="https://github.com/Fang-4-Group/Graduation-Project/assets/93365070/70215870-c1e7-4550-8727-a3f877971e64">

2024-03-30 13:44 UTC, frafishen commented
cd `src/db` should be the right path.

2024-03-30 13:56 UTC, frafishen requested changes

2024-03-30 13:56 UTC, frafishen commented on docker-compose.yml
> +    ports:
Nit: 理論上不應該把密碼名買放在程式碼中，比較好的作法應該是將帳密放在另外一個獨立的到地方，程式碼中要敲存放密碼的API去取得授權，不過這邊先會動就好了。我先開一張票，看之後有沒有人想要處理這個問題。

https://frafishen.atlassian.net/browse/GP-34

2024-03-30 13:56 UTC, frafishen commented on docker-compose.yml
> +      - "5432:5432"
我其實沒有很確定，但是我映射出來的port通常會長得不一樣。
因為之前如果設一樣，會顯示這個port已經被佔用？（就是裡面用了一次，外面就不能用）
但現在看起來好像可以，如果射不一樣的話，會壞掉嗎？

2024-03-31 03:04 UTC, yun-si commented on docker-compose.yml
> +      - "5432:5432"
意思是我把5432:至5432改成別的例如5430:5430之類的，然後看看build起來之後映射的port是甚麼，還能不能用這樣？

2024-03-31 03:48 UTC, yun-si commented on docker-compose.yml
> +      - "5432:5432"
`ports: 主機端口:容器端口`
主機端口可以更改（我用5430:5432測試沒壞），但容器端口改了就不能跑了

2024-03-31 05:41 UTC, frafishen commented on docker-compose.yml
> +      - "5432:5432"
先改成`ports: 主機端口:容器端口 = 5430:5432`吧。我覺得這樣看起來稍微比較合理。

容器端口跑了就不能跑，應該是因為你再起postgresql的伺服器的時候（就是下command的時候），沒有特別指定port，所以就預設是5432，所以你如果在docker上面改了port就會跑不起來。

2024-03-31 06:34 UTC, frafishen approved these changes

2024-03-31 13:42 UTC, merged